# Generated by Django 4.1.7 on 2023-03-26 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='usecases',
            name='category',
            field=models.CharField(choices=[('oem', 'Oem'), ('water_treatment', 'Water_treatment'), ('electronics_industry', 'Electronics_industry'), ('pharmaceutical_Bio', 'Pharmaceutical_Bio'), ('food', 'Food'), ('precision_machine', 'Precision_machine'), ('facility_management', 'Facility_management'), ('smart_Farm', 'Smart_Farm')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcategory'),
        ),
    ]
