# Generated by Django 4.1.7 on 2023-03-29 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_message_about_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manuals",
            field=models.URLField(
                default=datetime.datetime(
                    2023, 3, 29, 4, 2, 10, 924776, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usecases",
            name="category",
            field=models.CharField(
                choices=[
                    ("pharmaceutical_Bio", "Pharmaceutical_Bio"),
                    ("facility_management", "Facility_management"),
                    ("oem", "Oem"),
                    ("electronics_industry", "Electronics_industry"),
                    ("food", "Food"),
                    ("precision_machine", "Precision_machine"),
                    ("water_treatment", "Water_treatment"),
                    ("smart_Farm", "Smart_Farm"),
                ],
                max_length=50,
            ),
        ),
    ]
